version: '3.1'

services:

  db:
    image: postgres:10.13-alpine
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: markers_development,markers_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - markers_db_data:/var/lib/postgresql/data

volumes:
  markers_db_data:
