test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

aws_staging:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws_staging, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws_staging, :secret_access_key) %>
  region: <%= Rails.application.credentials.dig(:aws_staging, :region) %>
  bucket: <%= Rails.application.credentials.dig(:aws_staging, :bucket_name) %>

aws_dev:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:aws_dev, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws_dev, :secret_access_key) %>
  region: <%= Rails.application.credentials.dig(:aws_dev, :region) %>
  bucket: <%= Rails.application.credentials.dig(:aws_dev, :bucket_name) %>

amazon:
  service: S3
  access_key_id: <%= ENV['S3_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['S3_REGION'] %>
  bucket: <%= ENV['S3_BUCKET_NAME'] %>
